### ISSUE TITLE
ModUpdater changes donʼt seem to work

### ISSUE THREAD

**Issue by dhouck** [Fox2Code/FabricZero#7]
ModUpdater expects a specific name scheme for mod jar filenames, and many of the mods that this opts into ModUpdater donʼt seem to fit that scheme.  In *some* cases this could be fixed by adding `"strict": false` to the [injected JSON](https://github.com/Fox2Code/FabricZero/blob/0.1.3/src/main/java/com/fox2code/fabriczero/impl/ImplFabricZeroAPI.java#L81), but for others it would require much bigger changes.

I tested this on AppleSkin (which is perhaps one of the hardest mods to add here, since they maintain Forge compatibility and you need to go through the entry point version checking method to even have a hope of getting it to work), but this issue holds true for others too.

**Comment by Fox2Code** [comment]
`"strict": false` wasn't injected to avoid mod incompatibility
But I have an idea to "fix" that by detecting if the mod needs strict version checking or not

**Comment by dhouck** [comment]
You do a manual whitelist of what to add; you can go by whether `strict` is actually necessary or not.  But as-is, it just plain doesnʼt work for a lot of mods because (eg. Sodium) donʼt use the right version numbering scheme.  For example, the updater will think itʼs found Sodium version mc1.16.1 for Minecraft 0.1.0.

**Comment by Fox2Code** [comment]
The part of the code that manages this is in ModUpdater  
I will upstream ModUpdater improvement one day I just don't do it now because of lack of time.

**Comment by Fox2Code** [comment]
See #3
