### ISSUE TITLE
Mod makes trees grow weird.

### ISSUE THREAD

**Issue by Xrey274** [Fox2Code/FabricZero#8]
I am running 0.1.4(which i assume is the newest version) on minecraft 1.16.3. I have many other mods installed, but I have isolated FabricZero to be the culprit. It makes new trees, either from natural chunk generation or with sappling and bonemeal, grow in weird shapes.

**Comment by Fox2Code** [comment]
@Xrey274 I will try to test actually I had to stop FabricZero developement due to health problems
I will try to see what I can do to fix that

**Comment by Fox2Code** [comment]
Fixed -> https://github.com/Fox2Code/FabricZero/commit/6a409ec7c33d8d280a12aa2b29da57327a02c65f
